security:

    firewalls:
        frontend:
            pattern:    ^/*
            anonymous:  ~
            form_login:
                login_path: static_login
                check_path: usuario_login_check
                csrf_provider: form.csrf_provider
            logout:
                path: usuario_logout
                target: /
            remember_me:
                key: jwhf$$ui3627t5376$qwuy?
                lifetime: 3600
            

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/super/*, roles: ROLE_SUPER }
        - { path: ^/administracion/*, roles: ROLE_ADMIN }
        - { path: ^/area-cliente/*, roles: ROLE_USER }
        - { path: ^/perfil/*, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/mensaje/*, roles: [ROLE_ADMIN, ROLE_USER] }

    providers:
        chain_provider:
            chain:
                providers: [user_db, in_memory]
        user_db:
            entity: { class: Balongo\AdminBundle\Entity\Usuario, property: email }
        in_memory:
            memory:
                users:
                    - { name: webmaster@balongo.eu, password: balongo, roles: 'ROLE_SUPER' }

    encoders:
        Balongo\AdminBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User: plaintext
